### PR TITLE
fix: go 1.18 support

### PR DESCRIPTION
**Pull request by secDre4mer**

### CODE REVIEW

**Comment by TcM1911** [comment]
There are a few more items needed for 1.18 support:

- Moduledata parsing must be updated since the structure has changed.
- Update go.mod to 1.18
- Update buildinfo extraction to use the new package provided by the standard library.
- Investigate and update the type extraction
- Create golden 1.18 binaries for tests

Would you like to tackle some of these? Hopefully I can get some time to work on it soon.

**Comment by secDre4mer** [comment]
Yes, I can work on some of those. 

Should we merge the PR and keep track of the open issues in #54 or do you want to have one merge in the end with all the changes?

**Comment by TcM1911** [comment]
I've gotten some of it done. It's on the branch https://github.com/goretk/gore/tree/feature/go118. There are some test failures for the build info extraction on 1.18 binaries that I need to address. After that I need to check the type extraction. After that it should be done hopefully.

**Comment by TcM1911** [comment]
There is a working branch on #57

**Comment by secDre4mer** [comment]
Closing this in favor of the existing feature branch.

**Pull request closed without merging**
