### PR TITLE
feat: add brute force search fallback for elf

### LINKED ISSUE #76: gosym can provide the wrong address for funcs in cgo go binary
As described in https://github.com/golang/go/issues/65232, `gosym.NewLineTable` should be used with the value of symbol `runtime.text` but not just use the start of `.text` segment, which was used by gore right now.

I have no idea how to implement a search for `runtime.text` in the stripped binary, but at least we can show a warning like `the offset in func can be incorrect in cgo binary` right now.

image

### LINKED ISSUE #79: external linked pie elf binary can work without .gopclntab section
I'm playing with some golang compiler arguments, and I found a `linkmode=external buildmode=pie` bianry can work without `.gopclntab` section.

The example file placed at `https://github.com/Zxilly/go-testdata/releases/download/latest/bin-linux-1.21-amd64-ext-pie`, and the `readelf -S -W` reported as below.

```bash
There are 48 section headers, starting at offset 0x6ec970:

Section Headers:
  [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
  [ 1] .interp           PROGBITS        0000000000000350 000350 00001c 00   A  0   0  1
  [ 2] .note.gnu.property NOTE            0000000000000370 000370 000020 00   A  0   0  8
  [ 3] .note.gnu.build-id NOTE            0000000000000390 000390 000024 00   A  0   0  4
  [ 4] .note.ABI-tag     NOTE            00000000000003b4 0003b4 000020 00   A  0   0  4
  [ 5] .note.go.buildid  NOTE            00000000000003d4 0003d4 000064 00   A  0   0  4
  [ 6] .gnu.hash         GNU_HASH        0000000000000438 000438 000034 00   A  7   0  8
  [ 7] .dynsym           DYNSYM          0000000000000470 000470 000570 18   A  8   1  8
  [ 8] .dynstr           STRTAB          00000000000009e0 0009e0 000323 00   A  0   0  1
  [ 9] .gnu.version      VERSYM          0000000000000d04 000d04 000074 02   A  7   0  2
  [10] .gnu.version_r    VERNEED         0000000000000d78 000d78 000060 00   A  8   1  8
  [11] .rela.dyn         RELA            0000000000000dd8 000dd8 06cc78 18   A  7   0  8
  [12] .rela.plt         RELA            000000000006da50 06da50 000480 18  AI  7  26  8
  [13] .init             PROGBITS        000000000006e000 06e000 00001b 00  AX  0   0  4
  [14] .plt              PROGBITS        000000000006e020 06e020 000310 10  AX  0   0 16
  [15] .plt.got          PROGBITS        000000000006e330 06e330 000008 08  AX  0   0  8
  [16] .text             PROGBITS        000000000006e340 06e340 21efe7 00  AX  0   0 32
  [17] .fini             PROGBITS        000000000028d328 28d328 00000d 00  AX  0   0  4
  [18] .rodata           PROGBITS        000000000028e000 28e000 077370 00   A  0   0 32
  [19] .eh_frame_hdr     PROGBITS        0000000000305370 305370 00016c 00   A  0   0  4
  [20] .eh_frame         PROGBITS        00000000003054e0 3054e0 000690 00   A  0   0  8
  [21] .tbss             NOBITS          00000000003074d0 3064d0 000008 00 WAT  0   0  8
  [22] .init_array       INIT_ARRAY      00000000003074d0 3064d0 000008 08  WA  0   0  8
  [23] .fini_array       FINI_ARRAY      00000000003074d8 3064d8 000008 08  WA  0   0  8
  [24] .data.rel.ro      PROGBITS        00000000003074e0 3064e0 1c2750 00  WA  0   0 32
  [25] .dynamic          DYNAMIC         00000000004c9c30 4c8c30 0001f0 10  WA  8   0  8
  [26] .got              PROGBITS        00000000004c9e20 4c8e20 0001c8 08  WA  0   0  8
  [27] .data             PROGBITS        00000000004ca000 4c9000 008a50 00  WA  0   0 32
  [28] .go.buildinfo     PROGBITS        00000000004d2a50 4d1a50 000280 00  WA  0   0 16
  [29] .noptrdata        PROGBITS        00000000004d2ce0 4d1ce0 026722 00  WA  0   0 32
  [30] .bss              NOBITS          00000000004f9420 4f8402 02fea0 00  WA  0   0 32
  [31] .noptrbss         NOBITS          00000000005292c0 4f8402 006af0 00  WA  0   0 32
  [32] .comment          PROGBITS        0000000000000000 4f8402 00002b 01  MS  0   0  1
  [33] .debug_aranges    PROGBITS        0000000000000000 556680 000106 00   C  0   0  8
  [34] .debug_info       PROGBITS        0000000000000000 556788 09e24a 00   C  0   0  8
  [35] .debug_abbrev     PROGBITS        0000000000000000 5f49d8 000724 00   C  0   0  8
  [36] .debug_line       PROGBITS        0000000000000000 5f5100 05b2e1 00   C  0   0  8
  [37] .debug_frame      PROGBITS        0000000000000000 6503e8 011194 00   C  0   0  8
  [38] .debug_str        PROGBITS        0000000000000000 661580 0006a3 01 MSC  0   0  8
  [39] .debug_loc        PROGBITS        0000000000000000 661c28 06a159 00   C  0   0  8
  [40] .debug_ranges     PROGBITS        0000000000000000 6cbd88 0200ba 00   C  0   0  8
  [41] .debug_line_str   PROGBITS        0000000000000000 6ebe48 0001ec 01 MSC  0   0  8
  [42] .debug_loclists   PROGBITS        0000000000000000 6ec038 00066f 00   C  0   0  8
  [43] .debug_rnglists   PROGBITS        0000000000000000 6ec6a8 000084 00   C  0   0  8
  [44] .debug_gdb_scripts PROGBITS        0000000000000000 6ec72c 00003f 00      0   0  1
  [45] .symtab           SYMTAB          0000000000000000 4f8430 02a660 18     46 7124  8
  [46] .strtab           STRTAB          0000000000000000 522a90 033bed 00      0   0  1
  [47] .shstrtab         STRTAB          0000000000000000 6ec76b 000201 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  D (mbind), l (large), p (processor specific)
```

### PR DESCRIPTION
**Pull request by Zxilly**
Close: #79
Close: #76 

I did some test on the binaries. Seems the fallback only need for elf files.
On macho files, `__gopclntab` always exists.

```text
bin-darwin-1.11-amd64         : MACHO: __gopclntab
bin-darwin-1.11-amd64-ext     : MACHO: __gopclntab
bin-darwin-1.11-amd64-ext-pie : MACHO: __gopclntab
bin-darwin-1.11-amd64-pie     : MACHO: __gopclntab
bin-darwin-1.13-amd64         : MACHO: __gopclntab
bin-darwin-1.13-amd64-ext     : MACHO: __gopclntab
bin-darwin-1.13-amd64-ext-pie : MACHO: __gopclntab
bin-darwin-1.13-amd64-pie     : MACHO: __gopclntab
bin-darwin-1.15-amd64         : MACHO: __gopclntab
bin-darwin-1.15-amd64-ext     : MACHO: __gopclntab
bin-darwin-1.15-amd64-ext-pie : MACHO: __gopclntab
bin-darwin-1.15-amd64-pie     : MACHO: __gopclntab
bin-darwin-1.17-amd64         : MACHO: __gopclntab
bin-darwin-1.17-amd64-ext     : MACHO: __gopclntab
bin-darwin-1.17-amd64-ext-pie : MACHO: __gopclntab
bin-darwin-1.17-amd64-pie     : MACHO: __gopclntab
bin-darwin-1.19-amd64         : MACHO: __gopclntab
bin-darwin-1.19-amd64-ext     : MACHO: __gopclntab
bin-darwin-1.19-amd64-ext-pie : MACHO: __gopclntab
bin-darwin-1.19-amd64-pie     : MACHO: __gopclntab
bin-darwin-1.20-amd64-ext     : MACHO: __gopclntab
bin-darwin-1.21-amd64         : MACHO: __gopclntab
bin-darwin-1.21-amd64-ext     : MACHO: __gopclntab
bin-darwin-1.21-amd64-ext-pie : MACHO: __gopclntab
bin-linux-1.11-amd64          : ELF: .gopclntab
bin-linux-1.11-amd64-ext      : ELF: .gopclntab
bin-linux-1.11-amd64-ext-pie  : ELF: .data.rel.ro
bin-linux-1.11-amd64-pie      : ELF: .data.rel.ro
bin-linux-1.13-amd64          : ELF: .gopclntab
bin-linux-1.13-amd64-ext      : ELF: .gopclntab
bin-linux-1.13-amd64-ext-pie  : ELF: .data.rel.ro
bin-linux-1.13-amd64-pie      : ELF: .data.rel.ro
bin-linux-1.15-amd64          : ELF: .gopclntab
bin-linux-1.15-amd64-ext      : ELF: .gopclntab
bin-linux-1.15-amd64-ext-pie  : ELF: .data.rel.ro
bin-linux-1.15-amd64-pie      : ELF: .data.rel.ro.gopclntab
bin-linux-1.17-amd64          : ELF: .gopclntab
bin-linux-1.17-amd64-ext      : ELF: .gopclntab
bin-linux-1.17-amd64-ext-pie  : ELF: .data.rel.ro
bin-linux-1.17-amd64-pie      : ELF: .data.rel.ro.gopclntab
bin-linux-1.18-amd64          : ELF: .gopclntab
bin-linux-1.19-amd64          : ELF: .gopclntab
bin-linux-1.19-amd64-ext      : ELF: .gopclntab
bin-linux-1.19-amd64-ext-pie  : ELF: .data.rel.ro
bin-linux-1.19-amd64-pie      : ELF: .data.rel.ro.gopclntab
bin-linux-1.20-amd64-ext      : ELF: .gopclntab
bin-linux-1.21-amd64          : ELF: .gopclntab
bin-linux-1.21-amd64-ext      : ELF: .gopclntab
bin-linux-1.21-amd64-ext-pie  : ELF: .data.rel.ro
bin-windows-1.11-amd64        : PE: .rdata
bin-windows-1.11-amd64-ext    : PE: .rdata
bin-windows-1.13-amd64        : PE: .rdata
bin-windows-1.13-amd64-ext    : PE: .rdata
bin-windows-1.15-amd64        : PE: .rdata
bin-windows-1.15-amd64-ext    : PE: .rdata
bin-windows-1.15-amd64-ext-pie: PE: .rdata
bin-windows-1.15-amd64-pie    : PE: .rdata
bin-windows-1.17-amd64        : PE: .rdata
bin-windows-1.17-amd64-ext    : PE: .rdata
bin-windows-1.17-amd64-ext-pie: PE: .rdata
bin-windows-1.17-amd64-pie    : PE: .rdata
bin-windows-1.19-amd64        : PE: .rdata
bin-windows-1.19-amd64-ext    : PE: .rdata
bin-windows-1.19-amd64-ext-pie: PE: .rdata
bin-windows-1.19-amd64-pie    : PE: .rdata
bin-windows-1.20-amd64-ext    : PE: .rdata
bin-windows-1.21-amd64        : PE: .rdata
bin-windows-1.21-amd64-ext    : PE: .rdata
bin-windows-1.21-amd64-ext-pie: PE: .rdata
```

### CODE REVIEW

**Comment by Zxilly** [comment]
After #69 gets merged, tryFromSchedinit can be rewritten to based on symbol or dwarf.

**Comment by Zxilly** [comment]
@TcM1911 This patch adds some logic based on the symbol table. But most of the binary in the `https://github.com/goretk/testdata` are stripped and cannot be used to test.

I write a script to build different binaries for research at `https://github.com/Zxilly/go-testdata/blob/master/scripts/build.py`. Hope this can help `testdata` to provide more pre-compiled examples.

**Comment by TcM1911** [comment]
We need a solution that works for binaries without symbols. To support stripped binaries, we essentially need to find and process the PCLNTAB and the moduledata structures at the same time. Finding the PCLNTAB first is easiest because it starts with a set of magic bytes. So here is how I suggest going about this:

1. Find where the PCLNTAB is located.
2. Use the address to search for the moduledata since the first entry is the PCLNTAB address.
3. Once we have a possible moduledata location, check the fields for start and end of the code section. From a fast look, it appears that we only have two possible offset values between all the different moduledata structure versions. The values read must be within the text segment so we check that against the segments from the file header.
4. Once we have the start of "Go code section" we can parse the PCLNTAB and use that information to find the Go version followed by parsing the moduledata.

**Comment by Zxilly** [comment]
Currently it can work without symtab. But with symtab it works much more faster.

**Comment by Zxilly** [comment]
One major problem is that without symbol tables and debugging information, the extration of golang version can only rely on regular matches. But according to my research on compilers, buildinfo is usually at the very beginning and thus false positives are unlikely.

We could merge this now and add a brute force pattern matching pclntab scheme for case when golang version info is not found.

**Comment by Zxilly** [comment]
I would like to know if any progress has been made and I will continue to complete the brute force search fallback on this PR.

**Comment by Zxilly** [comment]
brute force search fallback for no goversion case has been added. Hope someone can review this.

**Comment by Zxilly** [comment]
I think there must be a bug in the code path of the symbol process, but it's hard to find it because the binary provided didn't include the unstrip version.

**Comment by Zxilly** [comment]
@TcM1911 any updates?

**Comment by TcM1911** [comment]
@Zxilly, sorry I've been very busy with other things. I actually got a chance to work on a solution to this myself today. I may have a chance to finish it tomorrow.

**Comment by TcM1911** [comment]
@Zxilly, check out this PR: https://github.com/goretk/gore/pull/90

**Comment by Zxilly** [comment]
Wait for #90 merged

**Pull request closed without merging**
