### PR TITLE
feat: support path handle on multi platform

### LINKED ISSUE #62: GetGoRoot return ErrNoGoRootFound when running on windows
in `goroot.go:357`, `subpath := fmt.Sprintf("/src/%s", v.Name)`, `subpath` will be `/src/:packageName`.
in `goroot.go:358`, `*github.com/goretk/gore.Package.Filepath` will return`\usr\local\go\src\:packageName`.
so in `goroot.go:358`, `if strings.HasSuffix(v.Filepath, subpath)` will alway be false.
image

if  i use this statement `subpath := filepath.Join("/src", v.Name)`, it will get expect result.
image

but, in `goroot.go:359`, it will return `\usr\local\go`, not equal `expectGoRoot` in `goroot_test.go`
in my project, i use `filepath.ToSlash` to deal with the result return from `GetGoRoot`. i have no idea, if use `filepath.ToSlash` in `goroot.go:360`, will it adversely affect the project?
image

i run `go test`, it seems good.
```
Running tool: go.exe test -timeout 30s -run ^TestExtractGoRoot$ github.com/goretk/gore

=== RUN   TestExtractGoRoot
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.10.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.11.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.12.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.13.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.14.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.5.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.6.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.7.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.7beta1
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.8.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.9.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.10.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.11.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.12.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.13.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.14.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.15.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.16.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.17.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.18.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.5.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.6.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.7.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.7beta1
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.8.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.9.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.10.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.11.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.12.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.13.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.14.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.15.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.16.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.17.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.18.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.5.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.6.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.7.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.7beta1
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.8.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-386-1.9.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.10.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.11.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.12.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.13.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.14.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.15.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.16.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.17.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.18.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.5.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.6.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.7.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.7beta1
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.8.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.9.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.10.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.11.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.12.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.13.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.14.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.15.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.16.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.17.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.18.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.5.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.6.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.7.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.7beta1
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.8.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-386-1.9.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.10.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.11.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.12.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.13.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.14.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.15.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.16.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.17.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.18.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.5.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.6.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.7.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.7beta1
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.8.0
=== RUN   TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.9.0
--- PASS: TestExtractGoRoot (0.74s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.10.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.11.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.12.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.13.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.14.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.5.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.6.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.7.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.7beta1 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.8.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-386-1.9.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.10.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.11.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.12.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.13.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.14.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.15.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.16.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.17.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.18.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.5.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.6.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.7.0 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.7beta1 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.8.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-darwin-amd64-1.9.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.10.0 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.11.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.12.0 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.13.0 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.14.0 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.15.0 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.16.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.17.0 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.18.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.5.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.6.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.7.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.7beta1 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.8.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-386-1.9.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.10.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.11.0 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.12.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.13.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.14.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.15.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.16.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.17.0 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.18.0 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.5.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.6.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.7.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.7beta1 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.8.0 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-linux-amd64-1.9.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.10.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.11.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.12.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.13.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.14.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.15.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.16.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.17.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.18.0 (0.00s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.5.0 (0.02s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.6.0 (0.02s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.7.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.7beta1 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.8.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-386-1.9.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.10.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.11.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.12.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.13.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.14.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.15.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.16.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.17.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.18.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.5.0 (0.02s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.6.0 (0.02s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.7.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.7beta1 (0.02s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.8.0 (0.01s)
    --- PASS: TestExtractGoRoot/get_goroot_form_gold-windows-amd64-1.9.0 (0.02s)
PASS
ok      github.com/goretk/gore  0.805s
```

### PR DESCRIPTION
**Pull request by Zxilly**
Closes: #62 

The previous version of gore included operations related to file paths, but it assumed that the user was running on Linux and processing the binary compiled from Linux. This patch adds support for Windows users, as Windows uses a different path separator.

### CODE REVIEW

**Comment by TcM1911** [comment]
I don't think this is an issue. The internal metadata, uses `/` in PE files too. Here is some extracted information for a Windows malware compiled on Windows:
```
$ redress info robbinhood 
OS         windows
Arch       i386
Compiler   1.11 (2018-08-24)
Build ID   S0jQf4QxsZWePWjYbNr_/yPyruULalESiVu0VcSmw/jFkudwhQ0JcJ_Yoy1Xuf/5XZga5N2LpIDGr7nhSbm
GoRoot     C:\Go
Main root  C:/Users/valery/go/src/oldboy
# main     1
# std      60
# vendor   2
```
Only the GoRoot has `\`.

Packages also uses `/`:
```
$ redress pkg --vendor robbinhood 
Packages:
Name  Version
----  -------
main  

Vendors:
Name                                    Version
----                                    -------
vendor/golang_org/x/crypto/cryptobyte   
vendor/golang_org/x/net/dns/dnsmessage  
```

Do you have a binary proving it is an issue?

**Comment by Zxilly** [comment]
To get an easy reproduce, just run the slowtest on a Windows machine. Some path classifier test will fail because they believe they found something like `\usr\local\go` (yes, the `filepath` join the path elements with `os.Separator:\`) but the expected value is `/usr/local/go`, which is indeed the real string in the binary. I think we should respect the raw data and keep the separator. 

I can add some detailed info about how this happened.

When using `filepath.Dir` to get the directory of the file, it will split the string with `/` or `\` then clean the relative paths, remove the last element and merge them.

The problem happened at the last step. It will join the elements with `os.Seperator`. But this was determined by the platform of the running golang binary but not the string itself. 

I noticed this and attached a debugger for a running instance of gore. Thus, I noticed the separator was `\` when it was a byte stream extracted from the binary and become `/` after the `filepath.Dir`. 

For redress, it use gore internal and also be affected by this.

**Comment by Zxilly** [comment]
@TcM1911 Do you have any comments?

**Comment by TcM1911** [comment]
You are right. I wasn't thinking of that condition.

We have test failures due to not knowing of the new go versions. Let's land #78 first. Once it has been merged, rebase so we can ensure the tests are passing.

**Comment by TcM1911** [comment]
It looks like some logic is broken. You can run the tests locally by using the `-tags slow_test`.

**Comment by Zxilly** [comment]
All tests passed on my Windows machine, I will retry with a linux instance.

**Comment by Zxilly** [comment]
I found the problem. In the past, generated package should have a path `<autogenerated>`, and `filepath.Dir` parse it as `.`. The two classifier both write based on this. I will also update the classifier.
image

**Comment by Zxilly** [comment]
All tests passed now. I updated some tests manually since they are likely get wrong value casued by `filepath.Dir("<autogenerate>")`.

It might be better to regenerate the test cases. It's hard to judge a `"."` filepath is the raw value or a `"<autogenerate>"` and `""` parsed result.

**Comment by TcM1911** [comment]
Actually, instead of implementing the OS free logic, I think we can use the [path](https://pkg.go.dev/path) package instead.
> Package path implements utility routines for manipulating slash-separated paths.
>
> The path package should only be used for paths separated by forward slashes, such as the paths in URLs. This package does not deal with Windows paths with drive letters or backslashes; to manipulate operating system paths, use the path/filepath package.

I need to think how we deal with the `filepath.Dir("<autogenerate>")` issue.

**Comment by Zxilly** [comment]
image

Seems just use `path` is ok, what's your opinion?

**Comment by TcM1911** [comment]
I prefer that over a self-implemented solution.

Sorry for all the back an forth.

**Comment by Zxilly** [comment]
updated

**Comment by Zxilly** [comment]
seems classifier needs a fix again

**Comment by Zxilly** [comment]
for `path.Dir()` we still need a wrapper

image

**Comment by Zxilly** [comment]
Can this PR be merged now? I'm developing on a Windows machine and the false positives on unit tests are annoying

**Comment by TcM1911** [comment]
Yes. It looks good now.

**Pull request merged**
