### PR TITLE
Add support for parsing and returning GoFunc value

### PR DESCRIPTION
**Pull request by derekparker**

### CODE REVIEW

**Comment by derekparker** [comment]
cc @TcM1911

**Comment by derekparker** [comment]
@TcM1911 looks like the failures are not related?

**Comment by TcM1911** [comment]
Correct, they are not related. It's failing because it's testing against 1.21 which the library doesn't have support for.

**Comment by TcM1911** [comment]
@derekparker, I just tagged [v0.11.2](https://github.com/goretk/gore/releases/tag/v0.11.2) that includes this.

**Comment by derekparker** [comment]
> @derekparker, I just tagged [v0.11.2](https://github.com/goretk/gore/releases/tag/v0.11.2) that includes this.

Thanks!

**Pull request merged**
